global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: touchstone-api
    static_configs:
      - targets: ["touchstone-api:8080"]
    metrics_path: /metrics

  - job_name: touchstone-worker
    static_configs:
      - targets: ["touchstone-worker:8080"]
    metrics_path: /metrics
